/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch DESIGN.md — Material Design 3 토큰 전체
        surface: '#fff8f1',
        'surface-dim': '#e2d9ca',
        'surface-bright': '#fff8f1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fcf2e3',
        'surface-container': '#f6eddd',
        'surface-container-high': '#f0e7d8',
        'surface-container-highest': '#ebe1d2',
        'on-surface': '#1f1b12',
        'on-surface-variant': '#524340',
        'inverse-surface': '#353026',
        'inverse-on-surface': '#f9f0e0',
        outline: '#85736f',
        'outline-variant': '#d7c2bd',
        'surface-tint': '#894f41',
        primary: '#894f41',
        'on-primary': '#ffffff',
        'primary-container': '#e89f8e',
        'on-primary-container': '#693529',
        'inverse-primary': '#ffb4a3',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a3',
        'on-primary-fixed': '#370e05',
        'on-primary-fixed-variant': '#6d382b',
        secondary: '#5f5e5f',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfe0',
        'on-secondary-container': '#636263',
        'secondary-fixed': '#e5e2e3',
        'secondary-fixed-dim': '#c8c6c7',
        'on-secondary-fixed': '#1c1b1c',
        'on-secondary-fixed-variant': '#474647',
        tertiary: '#8c4d3f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ed9d8c',
        'on-tertiary-container': '#6c3327',
        'tertiary-fixed': '#ffdad3',
        'tertiary-fixed-dim': '#ffb4a4',
        'on-tertiary-fixed': '#390c04',
        'on-tertiary-fixed-variant': '#70362a',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fff8f1',
        'on-background': '#1f1b12',
        'surface-variant': '#ebe1d2',
      },
      fontFamily: {
        'display-lg': ['Fraunces', 'serif'],
        'display-md': ['Fraunces', 'serif'],
        'headline-sm': ['Fraunces', 'serif'],
        'body-lg': ['Pretendard', 'sans-serif'],
        'body-md': ['Pretendard', 'sans-serif'],
        'body-sm': ['Pretendard', 'sans-serif'],
        'label-caps': ['Pretendard', 'sans-serif'],
        'mono-id': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        display: ['Fraunces', 'serif'],
        body: ['Pretendard', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '0.02em', fontWeight: '300' }],
        'display-md': ['32px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-id': ['13px', { lineHeight: '1', fontWeight: '400' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        'container-max': '800px',
        gutter: '20px',
      },
      maxWidth: {
        'container-max': '800px',
      },
    },
  },
  plugins: [],
};
